import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import SectionWrapper from "@/components/layout/section-wrapper";
import { createClient } from "@/lib/supabase/server";

const poppins = Poppins({
      subsets: ['latin'],
      display: 'swap',
      variable: '--font-poppins',
      weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] 
    });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = await createClient();
  const {data: {user}} = await supabase.auth.getUser();
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} antialiased lg:px-8 md:px-4 sm:px-2 px-2`}
      >
<Navbar user={user}/>
   

        {children}
        <Toaster position="top-right"/>

<Footer/>
      </body>
    </html>
  );
}
